### ISSUE TITLE
Missing view and download services in INSPIRE Geoportal

### ISSUE THREAD

**Issue by Vandapico** [INSPIRE-MIF/helpdesk-geoportal#186] opened 2024-02-16 11:09 UTC
Hello,
We have noticed that in the INSPIRE Geoportal many of our view or download services are missing, but we didn't changed anything and they've already had been showes in other times.
Example:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/160233194/7c8bc443-2a04-4d68-b60d-14cfdc28a17d)
[](https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/datasetdetails?country=pt&view=thematicOverview&theme=none&resourceId=28d58c90-5cde-4cac-87ac-37bf4e0ff3c5 )
In the metadata the services are referenced and the services are working, so we don't understand the problem.

Another question is, where we can check when has been done the last harvesting (Portugal), because now we can't find that information.

Best regards,

**Comment by jrc-inspire** [comment] 2024-02-23 00:49
Dear @Vandapico - Thank you for raising this issue. As part of the analysis of the revamped INSPIRE Geoportal which was launched on 24 November 2023, based on GeoNetwork Open Source version 4.2.6, the JRC also noticed the low accessibility indicators obtained by the newly delivered system.
To prevent this error from affecting Member States and EFTA countries during the INSPIRE Monitoring and Reporting 2023, an alternative approach for evaluating accessibility of datasets through view and download services was developed. It implements Part A of the Data-services linking simplification good practice. The approach will be explained in detail during the [77th MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/77th+MIG-T+meeting+2024-02-23).
In addition, we are working with the GeoNetwork community to improve the evaluation and processing of dataset accessibility in this software tool, capturing all lessons learnt and Member States’ feedback during the mentioned monitoring process in order to enhance the INSPIRE Geoportal.

**Comment by jescriu** [comment] 2024-05-14 14:36
Dear @Vandapico,
 
Two weeks ago a new contract was signed with Geocat for covering specific needs and improvements in the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu).

As part of this new collaboration with GeoCat, we will work in the integration of the accessibility results obtained through the corresponding [M&R tools](https://github.com/INSPIRE-MIF/mr-tools) in the system.

This work will start from next week and may end up in a revised server architechture, including a new sandbox enviroment.

More news wiil be provided in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17), on Friday 17 May.

**Comment by jescriu** [comment] 2024-05-14 15:18
This issue is considered a duplicate of #184.
Please refer to that issue for additional follow-up.

**Closed as completed by jescriu** 2024-05-14 15:18 UTC
Labels: duplicate
