### ISSUE TITLE
Dutch datasets are not displayed correctly under the INSPIRE themes

### ISSUE THREAD

**Issue by wboersma** [INSPIRE-MIF/helpdesk-geoportal#170] opened 2023-12-07 15:01 UTC
In the new Geoportal not all the Dutch datasets are published under the INSPIRE themes. 
For instance the theme Adressess, NL have 2 datasets, but none are shown under the INSPIRE theme Adressess. But when you look at the datasets at MS level, then the datasetse are in Geoportal.
How is this possible?

We have validated the datasets und they validate correctly.

MS-level:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/76045152/2bae16eb-0147-4df4-b8f0-ef79ae7a61cd)

Theme Addressess:
![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/76045152/82460db1-c60f-4dda-831f-d651c7c74b6d)

The same applies with other themes. for instance:  Cadastral parcels, Statistical units, Population distribution — demography,

**Comment by PB-GNM** [comment] 2024-02-05 15:41
In addition to this issue, we would like to know what criteria are used to decide wether a certain dataset is considered part of a theme and will there for be listed after a theme selection in the Geoportal.

We assume it has something to do with either the keywords, or the conformance, and the used title of the data specification in the conformance with this data specification or both. Sofar we were not able to determine which criteria are used on the bases of metadata of Dutch data sets that do come through and those that don't. 

Could you please give us the exact criteria, so we can at least explain to our data providers why data sets are not shown any more when certain themes are selected.

Of course we would prefer less strict criteria as it used to be when this problem did not occur, since it will cost a lot of effort to convince the data providers to change this in their metadata

**Comment by PB-GNM** [comment] 2024-04-15 09:58
In the meantime, we noticed that there is one clear distinction for all records that were not shown when selecting on a theme.
Those datasets have used an anchor like below: 

**<gmd:keyword>
       <gmx:Anchor xlink:href="http://www.eionet.europa.eu/gemet/nl/inspire-theme/su">Statistische eenheden</gmx:Anchor>
</gmd:keyword>**

Those without an anchor did appear in the Geoportal. 
We also saw a different anchor in a recent MIG-T presentation:

**<gmd:keyword>
       <gmx:Anchor xlink:href="https://inspire.ec.europa.eu/theme/su">Statistische eenheden</gmx:Anchor>
</gmd:keyword>**

So, we suppose that these should be changed.
Could you confirm that?

Best regards Pieter Bresters, Geonovum

**Comment by jescriu** [comment] 2024-04-15 10:20
Dear @PB-GNM,
Thank you for your findings. We will definitively investigate this, which is directly linked to the way GeoNetwork process INSPIRE theme keywords, and do the indexation in Elastic Search subsequently.
The INSPIRE Geoportal frontend filters are using directly the content indexed by Eleastic Search.

**Comment by PB-GNM** [comment] 2024-04-23 13:07
In the meanwhile, could you answer the following question with yes or no:

Is it still allowed to use <gmx:Anchor xlink:href="[http://www.eionet.europa.eu/gemet/nl/inspire-theme/su](http://www.eionet.europa.eu/gemet/nl/inspire-theme/su%22%3EStatistische)">Statistische eenheden</gmx:Anchor> as a Keyword?

**Comment by jescriu** [comment] 2024-05-27 08:31
Dear @PB-GNM,
I think this URL pattern is still accepted, but I will come back to you soon with an answer from the INSPIRE Validator team.
We will update the GeoNetwork indexation files used in the INSPIRE Geoportal accordingly, taking into account all possible URL patterns to declare the INSPIRE Themes.

**Comment by jescriu** [comment] 2024-07-08 07:46
Dear @wboersma, @idevisser, @PB-GNM,  

This issue was caused by the lack of interoperability in the use of code lists to declare the INSPIRE themes.
At this moment the community is using (at least) two types of code lists:

- http://www.eionet.europa.eu/gemet/<2-letter-country-code>/inspire-theme/<2-letter-country-INSPIRE-theme-code>- Thesaurus GEMET INSPIRE Themes (Eionet).
- http://inspire.ec.europa.eu/theme/<2-letter-country-INSPIRE-theme-code> - INSPIRE Registry.

The current versions of GeoNetwork are not incorporating the indexation of both types of code list as part of the indexation configuration files.

Since both types of code lists are allowed, last week we pushed to the INSPIRE Geoportal server the following fixes:

- https://github.com/geonetwork/core-geonetwork/blob/csw-remote-harvester/schemas/iso19139/src/main/plugin/iso19139/index-fields/index.xsl
- https://github.com/geonetwork/core-geonetwork/blob/csw-remote-harvester/web/src/main/webapp/xslt/common/index-utils.xsl

Now some INSPIRE NL datasets appear for the Addresses, Cadastral parcels, Statistical units and Population distribution — demography.

Please check if the indicator of number of dataset per themes is now as expected.
I will close this issue in one week if there are not further issues reported on this matter.

**Closed as completed** 2024-07-17 13:32 UTC
Labels: solved

**Comment by PB-GNM** [comment] 2024-07-30 11:06
Dear @jescriu,

Sorry for the late reaction. Due to holidays, we did not notice your update.
Thank you for solving this issue!
I have checked it on two themes. They both show the expected datasets.
