### ISSUE TITLE
unable to filter by facets

### ISSUE THREAD

**Issue by pvgenuchten** [INSPIRE-MIF/helpdesk-geoportal#166] opened 2023-11-15 11:53 UTC
## a description of the steps to reproduce your issue

https://inspire-geoportal.ec.europa.eu/results.html?country=de&view=details&theme=so
select the 'downloadable' or 'regional' filters, nothing happens, a javascript error occurs

```
Uncaught ReferenceError: qReginalSpatialScope is not defined
    at getSpatialScopeSolrFQParam (app_results.js:926:13)
    at S.fn.init.processSolrRequest (app_results.js:837:42)
    at sa (jquery.dataTables.min.js:37:33)
    at lb (jquery.dataTables.min.js:37:144)
    at P (jquery.dataTables.min.js:29:306)
    at T (jquery.dataTables.min.js:31:260)
    at Sb (jquery.dataTables.min.js:108:59)
    at s.<anonymous> (jquery.dataTables.min.js:108:458)
    at s.iterator (jquery.dataTables.min.js:100:126)
    at s.<anonymous> (jquery.dataTables.min.js:108:429)
```

## the browser and version used
windows - edge browser - Version 119.0.2151.58 (Official build) (64-bit)

## a screenshot illustrating the problem

![image](https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/299829/cbc013b6-bb06-4fb9-b1f9-45bf83a1b1e4)

## the URL of the page

https://inspire-geoportal.ec.europa.eu/results.html?country=de&view=details&theme=so

**Comment by jescriu** [comment] 2024-06-04 13:33
Dear @pvgenuchten,
I tried to reproduce this issue in MS Edge, but did not managed.
Indeed I found some cookies errors in the user interface, but not this javascript one - concretely on using the National / Regional filters. This functionality works for me.
Could you please clarify if the problem persist on your side?
Otherwise I will close the issue.

**Comment by pvgenuchten** [comment] 2024-06-11 23:03
Hi Jordi, thank you for your comment, I tried to replay my scenario, but the url posted above is not available anymore, a similar url is:
https://inspire-geoportal.ec.europa.eu/srv/eng/catalog.search#/results?country=de&view=themeOverview&theme=so

the result on that page does not load, on firefox the console shows these errors:
<img width="1085" alt="image" src="https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/299829/d3d1e4ae-f75d-4053-a3ed-ef373956c461">

on chrome i get these errors:
<img width="1132" alt="image" src="https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/299829/e2765746-b010-492a-85e0-75f8fafe8b2f">

The page itself looks like this:
<img width="978" alt="image" src="https://github.com/INSPIRE-MIF/helpdesk-geoportal/assets/299829/fa50a6d0-a309-4383-a98a-8614eb21957d">

what is interesting is that on a broken page as above, when i enable a filter, the search result does actually show up

Hope it helps

**Comment by jescriu** [comment] 2024-07-17 15:01
Dear @pvgenuchten,
I will pass this information to our ICT team to reproduce it and correct it if needed.

**Comment by jescriu** [comment] 2024-09-12 23:23
Dear @pvgenuchten, 
After an update of the INSPIRE Geoportal user interface made earlier today, this issue has been solved.

Please, verify that the issue is not reproduced anymore on your side, and re-open this thread in case the issue persists.

**Closed as completed by jescriu** 2024-09-12 23:23 UTC
Labels: solved, geoportal UI
