### ISSUE TITLE
Harvesting issue related to protection system

### ISSUE THREAD

**Issue by JulianaKar** [INSPIRE-MIF/helpdesk-geoportal#116] opened 2022-08-17 07:30 UTC
Dear Geoportal team,
We are implementing protection system on the National Geoportal.
In our opinion, realted to this we are now getting "Harvesting error" in the Inspire Geoportal harvest console with the message "Request for caching of /INSPIRE-106902a4-2bd0-11e9-a83c-52540023a883_20220810-121902/services/1 ended with status 400".
Is there any known https://www.cloudflare.com configuration issues regarding inspire harvest console?

**Comment by dartasensi** [comment] 2022-09-13 15:31
Dear @JulianaKar 

apologies for the late reply, but the team was on holidays, and then fully committed on the next release of the new Geoportal based on Geonetwork, so your request slipped through the cracks.

Last week, I did some tests on your endpoint. Indeed, I can confirm it: the issue is caused by your new Cloudflare protection. I think its feature commercial name might be Cloudflare Botfight protection.

From the Geoportal prospective, this support is not feasible in the current backend software. I also involved Geocat technical experts on this, to check the behaviour of Geonetwork and it is basically equivalent. We both expect the endpoint API (ie. GetCapabilities) to work flawlessly as a normal OGC CSW (ie. HTTP 200 response code and a valid xml response entity).

Technically speaking, when I try to contact your national point, it first answers with a HTTP 503 and the Cloudflare's proprietary challenge process, that obviously works within a browser, but not in our scenario (M2M).

I might suggest you to try and limit as much as possible this CF feature on that specific endpoint API (ie. GetCapabilities).

My two cents: maybe is it possibile in CF to setup its WAF properties, in order to check for common HTTP headers (eg. Accept : "application/xml")? So any OCG client can still get through this point, while keeping a minimal but effective protection against generic attacks or aggressive bots and crawlers.

Hope this will help you. I will leave this issue open so you can comment, if needed.
Thanks again for your patience.

Davide on behalf of the JRC INSPIRE Support

**Comment by jescriu** [comment] 2022-10-20 16:23
Dear @JulianaKar,
As we anticipated during the 2nd Training Q&A session on the new INSPIRE Geoportal backend, and during the 71st MIG-T meeting held on 7th October, we will come back to you soon by email to set up a bilateral meeting with the relevant national representatives for the discovery service of your country.
Therefore, given the detailed description of the reasons of this issue provided by @dartasensi, I proceed to close this it.

**Closed by jescriu** 2022-10-20 16:23 UTC
