### ISSUE TITLE
DE: request for a new harvesting

### ISSUE THREAD

**Issue by gdi-de-sara** [INSPIRE-MIF/helpdesk-geoportal#54] opened 2021-09-13 10:25 UTC
Dear Geoportal Helpdesk,

can you please start a new harvesting of our catalogue instance and publish them for us in the Geoportal harvesting "sandbox". The last harvesting process was more than 2 months ago. We actually wanted a harvest every 2 weeks. My colleague Mrs. Litka had contact with Davide (https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/49). But unfortunately nothing has happened for some time. 

Thanks in advance and best regards,

Sara Biesel (on behalf of SDI Germany)

**Comment by dartasensi** [comment] 2021-09-14 06:10
Dear Sara,

Apologies for the delay due to the summer break.
I managed to start (yesterday, around 16.09) a new harvest on my local machine.
Since the latest two attempts failed and, as you correctly stated, time passed by, I would prefer to see if the issue is still present, and tackle it immediately (in order to include this into the hotfix package we want to deliver soon).
At the moment, it is still running smooth.

Davide

**Comment by gdi-de-sara** [comment] 2021-09-14 06:34
Dear Davide,

thank you. I hope it goes through now.

Kind regards,
Sara

**Comment by SaGeissler** [comment] 2021-09-20 13:30
Hi Davide, 
following up on Sara's harvesting request of last week. Did you discover any issues during your attempt or was it successful?
What are the next steps in order to get updated information of our indicators as soon as possible?
Sabine

**Comment by jrc-inspire** [comment] 2021-11-11 08:36
We inform you that we are currently working in analyzing and addressing this issue, which has been identified as having a high priority considering its impact, with the aim of solving it in time for the upcoming INSPIRE Monitoring. 

We will approach you with more information as soon as possible.

As reported during the 67th MIG-T Meeting, the INSPIRE Geoportal is currently in a transition phase for the adoption of a fully-redesigned backend based on GeoNetwork. For this reason, we will limit the bug-fix/improvement actions on the current Geoportal to those issues having the highest impact and that can be addressed with the available resources.

**Comment by jescriu** [comment] 2021-12-09 15:12
Dear @gdi-de-sara / @SaGeissler,

After implementing some high effort performance improvements to the INSPIRE Geoportal code to deal with both, large catalogues and ATOM Feeds services we managed to successfully harvest the DE catalogue harvest we scheduled.

Please check the results. Hopefully you could publish them already.
Let us know the outcomes in order to proceed with closing this issue.

**Comment by alitka** [comment] 2021-12-10 16:57
Dear @dartasensi & @jescriu 
We've checked the results, and did the finally publishing. Therefore, you can close this issue.
Kind regards.

**Comment by jescriu** [comment] 2021-12-13 08:29
Thank you @alitka (and also @SaGeissler @gdi-de-sara) for your feedback.
We proceed to close this issue.

**Closed as completed by jescriu** 2021-12-13 08:29 UTC
Labels: harvest result, harvest request, harvest error
