### ISSUE TITLE
Start of INSPIRE Monitoring and Reporting 2021

### ISSUE THREAD

**Issue by jrc-inspire** [INSPIRE-MIF/helpdesk-geoportal#82] opened 2021-12-16 11:35 UTC
Dear all,
thank you for the continuous feedback and support provided in preparation of the Monitoring and Reporting 2021 exercise. Our team has made an exceptional work to address all requests, including those that came only few days before the deadline of 15/12.

Given that this deadline has now been reached, this message is to inform you that the harvest console will be closed and we will start harvesting all the catalogues and calculate the indicators. This operation will last for up to 3-4 weeks. Please make sure that during this time frame all the services are up and running.

Best regards,
JRC INSPIRE Team

**Comment by fdumortier** [comment] 2022-02-01 08:52
Dear JRC,
According to post above "(...) harvesting all the catalogues and calculate the indicators (...) will last for up to 3-4 weeks" starting from 15/12/2021. Can you give an update?  Today we are more than 7 weeks later and the harvest console is still unavailable...
Kind regards,
François Du Mortier

**Comment by fdumortier** [comment] 2022-02-07 15:56
Hello, the harvestconsole is back : thanks!

Howerever, it seems impossible to download the indicators (cfr https://inspire-geoportal.ec.europa.eu/harvestconsole/monitoring_indicators.jsp?gpResNew=INSPIRE-210556c9-36d4-11e1-aeeb-52540004b857_20211215-150102). The "Download indictors report" button is shown with a sandbox.

Kind regards,

François Du Mortier

**Comment by jescriu** [comment] 2022-02-15 18:12
Dear @fdumortier,

Thanks for pointing us to this issue, which was caused by a firewall that was denying some of the requests coming from the INSPIRE Geoportal. This firewall is a general JRC ICT component, i.e. outside the INSPIRE Geoportal architecture. 

Now the problem is solved. Please feel free to test it yourself by accessing to the Harvest Console for your endpoint (Service de découverte pour le catalogue Geobru), clicking on the 'Check and publish' button, and finally clicking on the 'Calculate indicators' button on the Harvesting report page.

You can access directly in this [URL](https://inspire-geoportal.ec.europa.eu/harvestconsole/monitoring_indicators.jsp?gpResNew=INSPIRE-210556c9-36d4-11e1-aeeb-52540004b857_20220208-155902), but notice that it will only remain valid till a new harvest is scheduled.

We proceed to close this issue, which was initially open as a news item to inform about the temporal unavailability of the harvest console during the Monitoring and Reporting processing period. Feel free to open a new issue in the helpdesk if the problem appears again.

**Closed as completed by jescriu** 2022-02-15 18:12 UTC
