### ISSUE TITLE
Problems with harvesting (Slovenia)

### ISSUE THREAD

**Issue by nppozar** [INSPIRE-MIF/helpdesk-geoportal#78] opened 2021-12-14 10:00 UTC
Dear INSPIRE team,

in harvesting we have a problem with download services that are not harvested to the geoportal. We have added many new services, but now the existing ones are also missing, the ones that have already been successfully published on the geoportal. Please help us, otherwise our monitoring results will not be correct.

Thank you very much and best regards,

Nina

**Comment by jescriu** [comment] 2021-12-15 17:21
Dear @nppozar,
Despite the late reporting of this issue, out IT Geoportal team will do our best to analyse and solve the problem (if it is due to the INSPIRE Geoportal).
We will keep you posted.

**Comment by nppozar** [comment] 2021-12-15 17:50
Thank you very much!

**Comment by nppozar** [comment] 2022-02-11 10:44
Dear @jescriu ,

Please let us know if you have been able to find out anything about our problems with harvesting download services. After re-establishing the harvesting console, we tried again yesterday and the problem remains.

Thank you very much and best regards,

Nina

**Comment by jescriu** [comment] 2022-02-15 13:28
Dear @nppozar,

Thank you for your new posting. We are now working in solving other issues, but we will be investigating if your issue may be the similar to #65. If this is the case, it might be regarded to the INSPIRE Reference Validator.

Will come back to you .

**Comment by nppozar** [comment] 2022-02-15 13:32
Dear @jescriu,

thank you, I think our case is not the same, because i have all validations green also on reference validator.

All the best,

Nina

**Comment by jescriu** [comment] 2022-02-15 13:42
OK. If this is confirmed we will treat it as a separate issue. 
We will let you know when we start analysing it.

**Comment by oberseri** [comment] 2022-02-16 10:15
> Dear @jescriu,
> 
> thank you, I think our case is not the same, because i have all validations green also on reference validator.
> 
> All the best,
> 
> Nina

Sorry to step into this discussion;

Did you validate the metadata or the DL-services (Atom-feeds) succesfully; to eliminate missunderstandings - we have a problem with the Atom-feed validation

Erik

**Comment by jescriu** [comment] 2022-02-23 14:41
Dear @nppozar,
Please kindly provide 2 or 3 examples of the services that are not harvested (also pointing to their metadata records).
Best,
Jordi

**Comment by nppozar** [comment] 2022-02-23 14:46
Dear @jescriu ,

in the meantime, we checked services once again and corrected a few things, which now results in successful harvesting.

Thank you again and best regards,

Nina

**Comment by jescriu** [comment] 2022-02-23 18:40
Dear @nppozar,
Great to hear that the issue is now resolved, which I proceed to close.
Could you enumerate which items you corrected in these services, and the type of services you amended? - This may help us in understanding the implications these items have in the INSPIRE Geoportal.
Thank you!

**Closed as completed by jescriu** 2022-02-23 18:40 UTC
