### ISSUE TITLE
Missing view and download services in INSPIRE Geoportal

### ISSUE THREAD

**Issue by Mi-I** [INSPIRE-MIF/helpdesk-geoportal#193] opened 2024-04-12 11:07 UTC
I see several  users have reported similar issues as we have, in posts titled eg "Missing view and download services in INSPIRE Geoportal".

Based on the answer given, I understand the solution is the "data-service linking simplification" planned in the next releases (2024.1 moved to April, or 2024.2). Could you please provide an update on whether the tests have been completed and the new ATS/ETS have been integrated into the system?

Thank you.
Swedish Transport Administration.

**Comment by jescriu** [comment] 2024-05-14 14:43
Dear @Mi-I,
 
Two weeks ago a new contract was signed with Geocat for covering specific needs and improvements in the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu).

As part of this new collaboration with GeoCat, we will work in the integration of the accessibility results obtained through the corresponding [M&R tools](https://github.com/INSPIRE-MIF/mr-tools) in the system.

This work will start from next week and may end up in a revised server architechture, including a new sandbox enviroment.

More news wiil be provided in the [78 MIG-T Meeting](https://wikis.ec.europa.eu/display/InspireMIG/78th+MIG-T+meeting+2024-05-17), on Friday 17 May.

Reading your sentence above:

> Based on the answer given, I understand the solution is the "data-service linking simplification" planned in the next releases (2024.1 moved to April, or 2024.2). Could you please provide an update on whether the tests have been completed and the new ATS/ETS have been integrated into the system?

I think you are probably mixing the INSPIRE Geoportal improvements (not subject at the moment to an explicit governance process) with the INSPIRE Reference Validator releases - For questions on the Validator, please refer to the [corresponding GitHub helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator/issues).

**Comment by jescriu** [comment] 2024-05-14 15:20
This issue is considered a duplicate of #184.
Please refer to that issue for additional follow-up.

**Closed as completed by jescriu** 2024-05-14 15:20 UTC
Labels: duplicate
